#!/usr/bin/zsh

typeset files="~/.local/share/applications/chrome-*-Profile_1.desktop"
typeset -A apps # key = app-id; value = App Name
typeset file
typeset id
typeset name

for file in ${~files}; do
  id="${${file#*chrome-}%-*.desktop}"
  name="$(sed -n 's/^Name=//p' ${file})"
  apps+=("${id}" "${name}")
done

name="$(echo ${(F)apps} | dmenu -i)"
id=${(k)apps[(r)${name}]}
[[ -n "${id}" ]] && exec /usr/bin/chromium --app-id=${id}
