#!/usr/bin/zsh

typeset profile=${1:-Default}
typeset files="~/.local/share/applications/chrome-*-${profile}.desktop"
typeset -A apps # key = app-id; value = App Name
typeset file
typeset id
typeset name

for file in ${~files}; do
  id="${${file#*chrome-}%-*.desktop}"
  name="$(sed -n 's/^Name=//p' ${file})"
  apps+=("${id}" "${name}")
done

name="$(echo ${(F)apps} | dmenu -i)"
id=${(k)apps[(r)${name}]}
[[ -n "${id}" ]] && \
  exec /usr/bin/chromium \
    --profile-directory=${profile} \
    --app-id=${id}
