#!/usr/bin/zsh

printf "\e[0mCOLOR_NC (No color)\n"
printf "\e[1;37mCOLOR_WHITE\t\e[0;30mCOLOR_BLACK\n"
printf "\e[0;34mCOLOR_BLUE\t\e[1;34mCOLOR_LIGHT_BLUE\n"
printf "\e[0;32mCOLOR_GREEN\t\e[1;32mCOLOR_LIGHT_GREEN\n"
printf "\e[0;36mCOLOR_CYAN\t\e[1;36mCOLOR_LIGHT_CYAN\n"
printf "\e[0;31mCOLOR_RED\t\e[1;31mCOLOR_LIGHT_RED\n"
printf "\e[0;35mCOLOR_PURPLE\t\e[1;35mCOLOR_LIGHT_PURPLE\n"
printf "\e[0;33mCOLOR_YELLOW\t\e[1;33mCOLOR_LIGHT_YELLOW\n"
printf "\e[1;30mCOLOR_GRAY\t\e[0;37mCOLOR_LIGHT_GRAY\n"
