#!/usr/bin/zsh -x
# TODO: document usage
# TODO: allow using an existing key
# TODO: use named arguments (eg: -cn, -an, --key-recipient)
# TODO: make conf output optional
# TODO: add option to use openssl098

function print_config {
  typeset -r CN="$1"
  shift
  typeset -r AN=("$@")

  << EOF
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no
encrypt_key = no
default_md = sha256

[req_distinguished_name]
C = US
ST = Virginia
L = Blacksburg
O = Virginia Polytechnic Institute and State University
OU = NI&S
CN = ${CN}

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
EOF
  
  # Intentional use of [ ... ] instead of [[ ... ]]
  # for an int only comparison
  if [ ${#AN} -gt 0 ];then
    echo
    echo "[alt_names]"
    for i in {1..${#AN}}; do
      echo "DNS.${i} = ${AN[i]}"
    done
  fi
}

typeset -r KEY_RECIP=(   '0xEB77F7CC0DBAF5F5' # waldrep@vt.edu
                      -r '0x38A2E59F337F062C' # stlee@vt.edu
                      -r '0x66FA534E2A83CAC8')# markhw@vt.edu
typeset -r OPENSSL="openssl"

${OPENSSL} req \
  -config <(print_config "$@" | tee $1.conf) \
  -new \
  -out $1.csr \
  -newkey rsa:2048 \
  -keyout >(gpg -ear ${KEY_RECIP} > "$1.key.asc")
