#!/usr/bin/zsh

typeset -r NB='#282828'
typeset -r NF='#ebdbb2'
typeset -r SB='#d79921'
typeset -r SF='#1d2021'

bemenu \
  --prompt='' \
  --scrollbar=autohide \
  --nb=$NB \
  --tb=$NB \
  --fb=$NB \
  --scb=$NB \
  --ab=$NB \
  --nf=$NF \
  --tf=$NF \
  --ff=$NF \
  --scf=$NF \
  --af=$NF \
  --sb=$SB \
  --hb=$SB \
  --sf=$SF \
  --hf=$SF \
  --no-overlap \
  --fn="Anonymous Pro" \
  --monitor=all \
  "$@"
