#!/usr/bin/zsh

typeset -r TMUX='/usr/bin/tmux'
typeset -r ST='/usr/bin/st'
typeset -r SESSION="[$(pwgen -s 4 1)]"

# Create a session with a known and unique name
$TMUX new -d -s "$SESSION"

# Send commands to the session using "$*" to pass as a single argument,
# instead of "$@" which we would normally want to preserve the word splits
[[ "$#" != 0 ]] && $TMUX send-keys -t "$SESSION" "$*" ENTER

# Open a terminal emulator and attach the desired session
exec $ST $TMUX attach -t "$SESSION"
