#!/usr/bin/zsh

if [[ "$#" < 3 ]]; then
  echo "Usage: $0 <filter> <file1> <file2> [diff options]"
  exit 1
fi

typeset filter="$1"
typeset file1="$2"
typeset file2="$3"
shift 3

[[ "$#" == 0 ]] && 1='-u'

diff \
  --color "$@" \
  <(jq "$filter" "$file1") \
  <(jq "$filter" "$file2")
