#!/usr/bin/zsh

typeset -a LINKS
typeset mac

for int in /sys/class/net/*; do
  [[ "$(cat $int/operstate)" == 'up' ]] && LINKS+=($int)
done

if [[ ${#LINKS} == 0 ]]; then
  exit 1
elif [[ ${#LINKS} > 1 ]]; then
  int=$(dmenu -p "Select an interface:" <<< ${(F)LINKS})
else
  int=$LINKS
fi

mac-formats $(cat $int/address)
