#!/usr/bin/env python3

import dmenu
import passpy
import subprocess
import sys
from typing import List

def main(argv: List[str]) -> int:
    copy(passpy.Store().get_key(dmenu.show(passpy.Store().find(''))).split('\n')[0])
    return 0

def copy(string: str) -> None:
    cmd = ['wl-copy', '--primary', '--paste-once', '--trim-newline', string]
    proc = subprocess.Popen(cmd, universal_newlines=True)

if __name__ == '__main__':
    sys.exit(main(sys.argv))
