#!/usr/bin/env bash

shopt -s nullglob globstar

typeset -r PREFIX=${PASSWORD_STORE_DIR-~/.password-store}
typeset -i typeit
typeset -a password_files

if [[ $1 == '--clip' ]]; then
  typeit=0
else
  typeit=1
  shift
fi

password_files=( "${PREFIX}"/**/*.gpg )
password_files=( "${password_files[@]#"${PREFIX}/"}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n "${password}" ]] || exit

if [[ "${typeit}" -eq 0 ]]; then
  pass show -c "${password}" 2>/dev/null
else
  pass show "${password}" \
    | head -n 1 \
    | xargs -d '\n' xdotool type --clearmodifiers --
fi
