#!/usr/bin/zsh

# This script will use dmenu to list the current tmux sessions
# The selected session will be opened in a new instance of st

typeset session

session=$(tmux list-sessions | dmenu -l 5 | cut -f 1 -d ':')

[[ -z "${session}" ]] || st -e tmux attach-session -t "${session}"
